linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    # - dupl
    - errcheck
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    - goconst
    - gocritic
    # - gocyclo
    # - godox
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - maligned
    - nakedret
    - prealloc
    # - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    # - unparam
    - unused
    - varcheck
    # - whitespace
    # - wsl
    # - gocognit

linters-settings:
  dogsled:
    # checks assignments with too many blank identifiers; default is 2
    # TODO: bring this down to at least 4
    max-blank-identifiers: 6
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  # errcheck: TODO: uncomment me and go through and check all errs
  #   # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
  #   # default is false: such cases aren't reported by default.
  #   check-blank: true
